### PR TITLE
Add support for UNLINK command

### PR DESCRIPTION
**Pull request by yozel**

### CODE REVIEW

**Comment by danysirota** [comment]
Can you merge this? UNLINK was added in Redis 4 and is a huge performance improvement.

Thanks

**Comment by yozel** [comment]
@danysirota I have created this pull request 7 months ago and don't know if this pull request will ever be merged anymore. Until then, you can use UNLINK feature in your project with execute_command method like this: `redis.execute_command('UNLINK', *names)`

**Comment by itamarhaber** [comment]
Hello @yozel,

Thanks for the PR - do not despair!

I believe registering the response callback in `RESPONSE_CALLBACKS` is missing - would you address that?

**Comment by andymccurdy** [comment]
Thanks. I'll merge and add the response callback since it's a one line change.

**Pull request merged**
