### PR TITLE
fix #708

### LINKED ISSUE #708: Got "TypeError: must be convertible to a buffer, not bytearray" in PyPy
```
PyPy version: 4.0.1 with GCC 4.8.4 on linux2
System: Ubuntu 15.04 x86 64bit
Error line: ./site-packages/redis/connection.py line 359 self._reader.feed(self._buffer, 0, bufflen)
```

``` pytb
Traceback (most recent call last):
  File "/home/zeno/amap/env/pypy/site-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/home/zeno/amap/env/pypy/site-packages/redis/connection.py", line 564, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/zeno/amap/env/pypy/site-packages/redis/connection.py", line 539, in send_packed_command
    self.connect()
  File "/home/zeno/amap/env/pypy/site-packages/redis/connection.py", line 447, in connect
    self.on_connect()
  File "/home/zeno/amap/env/pypy/site-packages/redis/connection.py", line 515, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/home/zeno/amap/env/pypy/site-packages/redis/connection.py", line 578, in read_response
    response = self._parser.read_response()
  File "/home/zeno/amap/env/pypy/site-packages/redis/connection.py", line 360, in read_response
    self._reader.feed(self._buffer, 0, bufflen)
TypeError: must be convertible to a buffer, not bytearray

```

Now I just move hiredis out, redis clients works no problem.

### PR DESCRIPTION
**Pull request by ethe**
https://github.com/andymccurdy/redis-py/issues/708

### CODE REVIEW

**Comment by youknowone** [comment]
This patch resolves my issue too in PyPy 4.0.1 / hiredis==0.1.4 / redis==2.10.5
The same code works without problem in Python 2.7.8 and same redis.

Question: Is any improvement required for this patch to be merged?

**Comment by andymccurdy** [comment]
@youknowone This is actually a hiredis-py issue. I created an issue there: https://github.com/redis/hiredis-py/issues/41

**Comment by Grokzen** [comment]
@andymccurdy If this is an hiredis issue and not issue for this repo, then consider closing this one as invalid.

**Comment by andymccurdy** [comment]
PyPy fixed their ByteArray support in version 5.3. hiredis-py (and redis-py with hiredis-py enabled) works with PyPy 5.3 or later.

**Pull request closed without merging**
