### PR TITLE
allow client to send remapped command

### PR DESCRIPTION
**Pull request by iandyh**
It's useful for redis-py to manage production Redis instances. 

usage:

```
renamed_commands = {
    'CONFIG GET': 'xxconfig get',
}
r = Redis(host='redis', port=6379, renamed_commands=renamed_commands)
```

### CODE REVIEW

**Comment by andymccurdy** [comment]
I don't understand why you would want to do this. Can you elaborate?

**Comment by iandyh** [comment]
Sure. For some companies like us, we renamed dangerous commands: `shutdown` -> `nevershutdown`. After renaming, server will not process any dangerous command sent from application side. However, we still need to perform certain commands for administration purposes. This is why I made the PR.

**Comment by andymccurdy** [comment]
I think this is better left to a special case in your code.

For what it's worth, if I needed something like this, I'd do the check within the `Connection` class so commands sent within pipelines are sanitized as well. And I'd also just raise an exception that explains that the command isn't available rather than renaming the command, which is going to produce a generic `RedisError` with a much more cryptic error message.

**Comment by iandyh** [comment]
@andymccurdy Adding renaming into `Connection` class would be needed. The exceptions are not needed since a `CommandError` will be thrown anyway and that's enough. 

IMO, the changes are still helpful otherwise it will be difficult for administrators to perform certain operations.

**Pull request closed without merging**
