### PR TITLE
Added support for the MONITOR command

### PR DESCRIPTION
**Pull request by kisabaka**
Implemented the MONITOR command in a similar way to PubSub, using a generator to get the messages.

### CODE REVIEW

**Comment by RoeyPrat** [comment]
@dougk7 - Hi, would you like me to rebase this PR? I think this is important.

**Comment by dougk7** [comment]
@RoeyPrat sure thing. I haven't used redis-py since 2011 :)

**Comment by gyermolenko** [comment]
superceded by #1033 mentioned above and is probably obsolete by now.
Maybe a candidate for close?

**Comment by RoeyPrat** [comment]
closing as obsolete, due to #1033

**Pull request closed without merging**
