### PR TITLE
[Optimize] Rename ambiguous param name in func eval

### PR DESCRIPTION
**Pull request by unbeatablekb**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Does travis tests pass with this change (enable it first in your forked repo and wait for the travis build to finish)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### Description of change

I think params here maybe a little ambiguous for people who are not familiar to luajit in redis. 

So I open this pr : )

### CODE REVIEW

**Comment by andymccurdy** [comment]
`keys_num` seems worse to me. If we really wanted to be more verbose, `number_of_keys` would be better.

However, I don't see why we need to do this. It potentially breaks backwards compatibility for anyone passing this value as a named argument. Additionally, I assume that nearly everyone who uses Lua scripting with redis-py uses the builtin `Script` object.

**Comment by unbeatablekb** [comment]
Thanks for your comment : )

I read docmenation and code again after receive your cooment. Useing `Script` object is a good idea since I had nearly no concept about it.

I will close this pr soon.

`It potentially breaks backwards compatibility for anyone passing this value as a named argument.` I still don't understand it. Do you mean keep `numkeys`  stay coordinate with `keys_and_args` ?

**Comment by andymccurdy** [comment]
I don’t believe we should change the name of an argument unless we have a very good reason for doing so.

**Comment by unbeatablekb** [comment]
Thanks.

**Pull request closed without merging**
