### PR TITLE
WIP: Add redis_url command line argument for tests

### PR DESCRIPTION
**Pull request by gyermolenko**
It is convenient to be able to run tests against particular redis-server, like
`$ pytest tests/test_commands.py --redis-url="redis://localhost:6371/9"`

It should work if you have several running redises, e.g.
`$ docker run --rm -p 6371:6379 redis:5.0.1`
`$ docker run --rm -p 6375:6379 redis:5.0.5`

Unfortunately these changes do not cover situation when redis version is  < 5, because of 
`get_info()` and `skip_if_` helpers.

Please let me know what you think.

Also: ref #503

### CODE REVIEW

**Comment by andymccurdy** [comment]
@gyermolenko Could we simply make `get_info()` accept the `r` fixture, which would then use the connection provided by the url? That would then allow all the `skip_*` decorators to work.

**Comment by gyermolenko** [comment]
At the moment `get_info()` has a couple of weird traits: 
- uses hardcoded connection parameters
- relies on `client.info()` which theoretically can break after some changes in the lib
- uses global variable `_REDIS_INFO` 

This is why I'm not sure about it. I'll try to come up with smth different here or in another PR

**Comment by andymccurdy** [comment]
If `get_info()` used the `r` fixture, we could eliminate the hardcoded connection params. And it only uses the global `_REDIS_INFO` to cache the result after the first lookup. I think it's safe to assume we're only talking to a single Redis server in the existing test suite.

**Comment by gyermolenko** [comment]
once `get_info` uses `r` it should become either test or fixture.
But it is used in skip-calculating functions directly.

For skips there are other approaches.
Separate module, markers, `pytest_collection_modifyitems`.

**Comment by andymccurdy** [comment]
I'm fine merging a patch that allows the connection info to be specified on the command line. But the current patch fails when specifying a connection string that's different than localhost:6379 as get_info will still be looking at the localhost.

We need to fix that before this can be merged IMO.

**Comment by gyermolenko** [comment]
Added example on how we can infer redis version on start and use it in tests.
If you are ok with that - I will update PR a little bit.

**Comment by andymccurdy** [comment]
Sure, this looks good to me. I didn't know about `pytest_sessionstart()`. Seems like it's a great fit for what we need.

I assume we can continue to use the `skip_if_server_version_lte` decorator and just update its implementation. It's slightly more convenient than the more verbose `pytest.mark.skipif` + conditional check.

And we'll also need to make sure the server's `arch_bits` value is contained within `REDIS_INFO` and update the `skip_unless_arch_bits` decorator as well.

Thanks!

**Comment by gyermolenko** [comment]
Ok, done.
Worth noting:
I've run test suite against 5.0.1 (passed) and 4.0.0 - `test_monitor` failed because `CLIENT ID` was introduced in 5.0.0 and there is no skip.

**Comment by gyermolenko** [comment]
I would also like to propose the variant of `r` fixture with "setup / yield / teardown" instead of  `_get_client` version with finalizer.
```python3
@pytest.fixture
def r(pytestconfig):
   redis_url = pytestconfig.getoption("--redis-url")
   client = redis.Redis.from_url(redis_url)
   yield client
   client.flushdb()
   client.connection_pool.disconnect()
```

**Comment by gyermolenko** [comment]
Testing with different versions of redis 
(`pytest tests/ --redis-url="redis://localhost:637x/9" -rs`)

5.0.0 - ok
5.0.1 - ok
5.0.2 - ok
5.0.3 - 1 fail at `tests/test_pubsub.py:315: TestPubSubMessages.test_unicode_channel_message_handler`
5.0.4 - ok
5.0.5 - ok

**Comment by andymccurdy** [comment]
Looks good to me. I'm fine with the setup/yield/teardown generator style fixture if you want to change it.

re: the 5.0.3 pubsub test failure -- is this something that's consistently reproducible on that version? I haven't seen it before.

**Comment by gyermolenko** [comment]
> I'm fine with the setup/yield/teardown generator style fixture if you want to change it.
will probably do that in separate PR

> the 5.0.3 pubsub test failure -- is this something that's consistently reproducible on that version?
hmmm , sorry. Just rerun it 5 times - no errors. A bit strange

**Comment by andymccurdy** [comment]
Sounds good. I'll merge once Travis finishes.

**Comment by andymccurdy** [comment]
Thanks for this!

**Pull request merged**
