### PR TITLE
Test against pypy and pypy3

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
@erickponce in the issue #734 I asked you about the pypy support, but the travis aren't testing using pypy.

What do you think about merge it?

**Comment by thedrow** [comment]
If this is not going to be merged, should we open an issue about it?

**Comment by abrookins** [comment]
We test against pypy now, using the new Docker-based testing setup, so I
think we’re good!

**Comment by RoeyPrat** [comment]
@thedrow take a look in the recent logs. if changes are still needed, please let us know
https://travis-ci.org/github/andymccurdy/redis-py/builds/711607577#L661

**Comment by thedrow** [comment]
Everything seems to be in order.
Thank you.

**Pull request closed without merging**
