### PR TITLE
add url support for sentinel

### PR DESCRIPTION
**Pull request by feifangit**
Enhanced `from_url` function in utils.py. Support fetch a sentinel object or  master redis node.

With the ability to get master redis node from url, other libraries based on redis-py are able to benefit from redis sentinel feature, including django-redis-cache and redis backend in celery etc.

Return sentinel object if not service_name provided in url

``` python
>>> redis.from_url('sentinels://10.1.2.122:17700')
Sentinel<sentinels=[10.1.2.122:17700]>
>>> redis.from_url('sentinels://node1:17700,node2:17700')
Sentinel<sentinels=[node1:17700,node2:17700]>
```

Return master node if service_name provided in url

``` python
>>> redis.from_url('sentinels://node1:17700,node2:17700?service_name=mymaster', db=1)
StrictRedis<SentinelConnectionPool<service=mymaster(master)>
```

you can pass same parameters used in `Sentinel.master_for` by parameter `master_for_args` in new `from_url`, of course, we can consider not to put `master_for_args` parameter in function declaration explicitly.

``` python
>>> redis.from_url('sentinels://node1:17700,node2:17700?service_name=mymaster', db=1, master_for_args={'redis_class':redis.Redis})
Redis<SentinelConnectionPool<service=mymaster(master)>
```

### CODE REVIEW

**Comment by jonathansp** [comment]
@andymccurdy did you have any chance to take a look at it?

**Comment by cristianoliveira** [comment]
:+1:

**Comment by Duologic** [comment]
This looks great, any chance this would get into master any time soon? 

I've see a different method of describing the URL in Kombu (eg. Celery): http://docs.celeryproject.org/projects/kombu/en/latest/changelog.html?highlight=sentinel

They do it like this:

`sentinel://:s3cr3t@192.168.0.1:26379/2;sentinel://:s3cr3t@192.168.0.2:26379/2;sentinel://:s3cr3t@192.168.0.3:26379/2`

It might be interesting to look at their implementation.

**Comment by feifangit** [comment]
I think `redis-py` can support the sentinel URL whatever the format is. otherwise, you will see many kinds of implementation

**Comment by Duologic** [comment]
I'm sorry, I don't understand what you mean. Do you propose that redis-py should implement several types of sentinel URLs?

At the moment I already see 3 types of implementations, see the Kombu example above, the proposal in this pull request and for example django-redis-sessions doesn't even implement a URL-like structure:

```
SESSION_REDIS_SENTINEL_LIST = [(host, port), (host, port), (host, port)]
SESSION_REDIS_SENTINEL_MASTER_ALIAS = 'sentinel-master'
```

**Pull request closed without merging**
