### PR TITLE
set weight of sentinel nodes balancer, avoid the first sentinel node too busy

### PR DESCRIPTION
**Pull request by BingerCoder**
As the order of sentinel in queue,the first sentinel node always received more connections,so shuffle the sentinel to make balance as same as possible.

### CODE REVIEW

**Comment by 5977862** [comment]
In our project, use three sentinel nodes,and so many connections in first sentinel node,the other two sentinel nodes almost haven't no connections.

SO 

1.First node is very busy and left nodes are very free.High load make more wait tasks,more wait tasks make more load~ vicious cycle~
2.If first node crash down, all connections are unused,but if we balance them,just part of them are unused.

I think it is useful~

**Comment by MrKiven** [comment]
there more other things to do, like:

1. set a weight for every nodes
2. record connections, then pick least connections node
3. just `random.choice`

just my point 😄

**Comment by 5977862** [comment]
I think the first point is good,set weight for nodes can choice best one we knew.     

If use random,connections of every node may as many as same.Or we can set weight for every nodes,it still be a predictable rate~

So I don't support the second point~   

😋

**Comment by MrKiven** [comment]
> I think the first point is good,set weight for nodes can choice best one we knew.

yeah..weighted round robin..

**Comment by 5977862** [comment]
thank you for your advice,I will change this pr ~

**Pull request closed without merging**
