### PR TITLE
Drop Python 2.6 support

### PR DESCRIPTION
**Pull request by jdufresne**
Remove 2.6 workarounds. Update testing configurations. Use modern Python syntax where available:

* Use set literals
* Use dict comprehensions
* Use more generators
* Use `io` package for `BytesIO`
* Remove `from __future__ import with_statement`
* Use unicode literals throughout

Thanks Dustin Ingram for the original patch.

---

 This is a continuation of the work started by @di in #796. I have rebased the patch and addressed a couple other cleanups I saw. I'll happily close this PR if the other work continues.

### CODE REVIEW

**Comment by hugovk** [comment]
Here's the pip installs for redis from PyPI for the last month, showing low numbers for 2.6:
```
$ pypinfo --percent --pip redis pyversion
python_version percent download_count
-------------- ------- --------------
2.7              63.2%        849,343
3.5              18.2%        244,235
3.6              12.1%        162,059
3.4               5.6%         75,033
2.6               0.8%         11,297
3.3               0.1%            821
3.7               0.1%            681
3.2               0.0%            203
None              0.0%             56
3.1               0.0%              1
```

3.3 also went EOL last month and has even lower numbers.

**Comment by jdufresne** [comment]
I'm happy to also drop support for Python 3.3 if it is agreeable with the project maintainers. @andymccurdy what do you think?

**Comment by Grokzen** [comment]
@jdufresne you should really split all changes in this MR into separate commits where you in each commit fix each of the lines in your list in the first comment. That would make it much easier to review compared to now where it is just one big commit with 19 files changed.

**Comment by jdufresne** [comment]
@Grokzen I've split the commit to several smaller commits. Each commit tries to handle a single focused aspect of the change. Please review.

**Comment by zeebonk** [comment]
There are a couple of functions on the client that accept timedeltas that get converted to seconds/milliseconds by manual calculation, e.g. in client.py:1212

    time = time.seconds + time.days * 24 * 3600

With the introduction of timedelta.total_seconds() in py2.7 this can be changed to:

    time = int(time.total_seconds())

etc.

**Comment by jdufresne** [comment]
@zeebonk, good call. Thanks for reviewing. I've added two new commits. One to use `timedelta.total_seconds()` and one to remove Python 3.3 support.

I've also rebased all commits to the latest master.

**Comment by hugovk** [comment]
Here's pip installs for redis from PyPI for May 2018, Python 2.6 downloads are down 61% since October:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  59.33% |        433,625 |
| 3.6            |  23.73% |        173,461 |
| 3.5            |  10.09% |         73,732 |
| 3.4            |   6.09% |         44,484 |
| 2.6            |   0.61% |          4,442 |
| 3.7            |   0.08% |            574 |
| 3.3            |   0.05% |            362 |
| 3.2            |   0.02% |            138 |
| None           |   0.00% |             16 |
| 3.8            |   0.00% |              1 |
| Total          |         |        730,835 |

Source: `pypinfo --start-date 2018-05-01 --end-date 2018-05-31 --percent --markdown redis pyversion`

**Comment by andymccurdy** [comment]
I'm going to look at this tomorrow or over the weekend. I would very much like to drop support for 2.6 and 3.3. Thanks for the work on this.

**Comment by andymccurdy** [comment]
@jdufresne @di Thanks so much for the effort on this. Super helpful. Merged.

**Pull request merged**
