### PR TITLE
Implement PUBSUB * commands

### PR DESCRIPTION
**Pull request by AngusP**
PUBSUB CHANNELS, PUBSUB NUMSUB and PUBSUB NUMPAT are implemented as per https://redis.io/commands/pubsub and suggested in Issue #526.

### CODE REVIEW

**Comment by andymccurdy** [comment]
This looks great, thanks. One request: can you add a `@skip_if_server_version_lt` decorator to the tests so that they only run when testing against a compatible server? For reference: https://github.com/andymccurdy/redis-py/blob/master/tests/test_commands.py#L62

Happy to merge afterwards.

**Comment by AngusP** [comment]
Hi @andymccurdy, sure, I'll do that and push soon

**Comment by AngusP** [comment]
@andymccurdy added and pushed, builds passing

**Comment by andymccurdy** [comment]
thanks. merging.

**Pull request merged**
