### PR TITLE
Drop Python 2.6 support

### PR DESCRIPTION
**Pull request by di**
Yesterday marks 3 years since the last release of Python 2.6! 🎉

To celebrate, I'm attempting to drop support for it from 156 prominent Python packages (one for every week it's past end-of-life)--including this one!

I've tried my best to remove as much 2.6-specific cruft as I can, but at the very least, this PR will remove the `'Programming Language :: Python :: 2.6'` trove classifier from this projects `setup.py`.

### CODE REVIEW

**Comment by Grokzen** [comment]
@di Should this prompt for a new major version if this would be considered to be merged? From the resistance you have encountered so far, i think that redis-py might be on the "stay" side of this topic, but who know what andy thinks =) This lib might be to big to drop support for the older python versions similar to responses from raven and requests.

**Comment by andymccurdy** [comment]
Thanks for the work on this. The cleanups are nice.

I'd like to take a look at what other widely used projects are doing. Do you have links to feedback from other maintainers?

If we merge this, it won't happen until 3.0.

**Comment by Grokzen** [comment]
@andymccurdy You can see the open PR:s di has done so far if you look at his profile and scroll down a bit https://github.com/di it shows the few that has been denied and most of them are still open.

**Comment by di** [comment]
@Grokzen That's a hard question for me to answer. If I were a 2.7+ user, I wouldn't expect this change to necessitate a new major version, but if I were a 2.6 user, it would very much be a breaking change.

@andymccurdy I've generally gotten resistance to my celebratory PRs, but a number of projects have recently dropped support for 2.6:

* https://github.com/PyCQA/flake8/commit/a1c1247cba53e8e3160f00b9e923db5b36b3d131
* https://github.com/Pylons/pyramid/pull/2759
* https://github.com/pypa/twine/commit/a935951825ee3b405238cd18f9ec845e74bb7e8c

And more notably, `pip` just turned on a deprecation warning for 2.6 for the upcoming 9.0 release: https://github.com/pypa/pip/pull/4047

**Comment by hugovk** [comment]
Maybe time to fix the merge conflict and then merge? The pending pip 10 will be dropping 2.6.

**Comment by hugovk** [comment]
By the way, here are the pip installs for last month:
```
$ pypinfo --percent --pip redis pyversion
python_version percent download_count
-------------- ------- --------------
2.7              65.8%        929,968
3.5              16.8%        237,095
3.6              10.9%        153,760
3.4               5.5%         77,624
2.6               0.8%         11,871
3.3               0.1%            958
3.7               0.1%            736
3.2               0.0%            350
None              0.0%             43
3.1               0.0%              1
```

(3.3 went EOL last month.)

**Comment by jdufresne** [comment]
As this work looks outdated and in stalled I've continued it in PR #916. If this work continues, I'll happily close the other PR.

**Comment by di** [comment]
Thanks @jdufresne!

**Pull request closed without merging**
