### PR TITLE
speedup 50% with pack_command rewritten in cython.

### PR DESCRIPTION
**Pull request by yihuang**
This c extension module is totally optional, and don't got build as default, so don't have any downside for normal user who don't need speedup.
And if you wants speedup, you need to install cython 0.19 (which is the only cython version i tested), and run `cython redis/_pack.pyx`, before `python setup.py install`.
I also included a socket mockup module which support packet recording and replay, and a profile script.
Below is the timeit and profile result run on my mba laptop:

```
> cd benchmark
> export PYTHONPATH=..
> python benchmark.py
```

Original `pack_command`:

```
10000 loops, best of 3: 57.2 usec per loop
         620002 function calls in 1.106 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10000    0.283    0.000    0.579    0.000 connection.py:45(_pack_command)
   180000    0.147    0.000    0.147    0.000 {method 'write' of 'cStringIO.StringO' objects}
    10000    0.083    0.000    0.987    0.000 client.py:387(execute_command)
    10000    0.073    0.000    0.129    0.000 connection.py:206(read_response)
    30000    0.066    0.000    0.101    0.000 connection.py:33(_encode)
    80000    0.048    0.000    0.048    0.000 {isinstance}
    10000    0.038    0.000    0.240    0.000 client.py:402(parse_response)
    10000    0.034    0.000    0.654    0.000 connection.py:333(send_command)
    10000    0.030    0.000    1.017    0.000 client.py:777(set)
    10000    0.028    0.000    0.166    0.000 connection.py:337(read_response)
    10000    0.025    0.000    0.041    0.000 connection.py:314(send_packed_command)
    10000    0.024    0.000    0.024    0.000 patch_socket.py:17(start_replay)
    10000    0.024    0.000    1.087    0.000 benchmark.py:38(run_with_replay)
    10000    0.022    0.000    1.039    0.000 benchmark.py:28(bench)
        1    0.019    0.019    1.106    1.106 <string>:1(<module>)
    10000    0.019    0.000    0.035    0.000 client.py:261(<lambda>)
    40000    0.019    0.000    0.019    0.000 _compat.py:21(<lambda>)
    10000    0.016    0.000    0.022    0.000 patch_socket.py:40(recv)
    50000    0.015    0.000    0.015    0.000 {len}
    10000    0.013    0.000    0.016    0.000 patch_socket.py:34(sendall)
    20000    0.013    0.000    0.013    0.000 {method 'gets' of 'hiredis.Reader' objects}
    10000    0.013    0.000    0.016    0.000 _compat.py:18(<lambda>)
    10000    0.011    0.000    0.011    0.000 {method 'endswith' of 'str' objects}
    10000    0.010    0.000    0.010    0.000 {cStringIO.StringIO}
    10000    0.009    0.000    0.009    0.000 {method 'feed' of 'hiredis.Reader' objects}
    10000    0.008    0.000    0.008    0.000 {method 'getvalue' of 'cStringIO.StringO' objects}
    10000    0.006    0.000    0.006    0.000 {method 'pop' of 'list' objects}
    10000    0.005    0.000    0.005    0.000 benchmark.py:11(get_connection)
    10000    0.005    0.000    0.005    0.000 benchmark.py:14(release)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

Optimized pure python `pack_command`:

```
10000 loops, best of 3: 46.1 usec per loop
         580002 function calls in 0.983 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10000    0.247    0.000    0.450    0.000 connection.py:45(_pack_command)
    10000    0.080    0.000    0.864    0.000 client.py:387(execute_command)
    10000    0.074    0.000    0.132    0.000 connection.py:203(read_response)
    30000    0.065    0.000    0.098    0.000 connection.py:33(_encode)
   150000    0.050    0.000    0.050    0.000 {method 'append' of 'list' objects}
    80000    0.047    0.000    0.047    0.000 {isinstance}
    10000    0.038    0.000    0.243    0.000 client.py:402(parse_response)
    10000    0.036    0.000    0.530    0.000 connection.py:330(send_command)
    10000    0.031    0.000    0.895    0.000 client.py:777(set)
    10000    0.028    0.000    0.044    0.000 connection.py:311(send_packed_command)
    10000    0.028    0.000    0.170    0.000 connection.py:334(read_response)
    10000    0.024    0.000    0.964    0.000 benchmark.py:38(run_with_replay)
    10000    0.024    0.000    0.024    0.000 {method 'join' of 'str' objects}
    10000    0.024    0.000    0.024    0.000 patch_socket.py:17(start_replay)
    10000    0.021    0.000    0.916    0.000 benchmark.py:28(bench)
    10000    0.019    0.000    0.036    0.000 client.py:261(<lambda>)
        1    0.019    0.019    0.983    0.983 <string>:1(<module>)
    40000    0.018    0.000    0.018    0.000 _compat.py:21(<lambda>)
    50000    0.016    0.000    0.016    0.000 {len}
    10000    0.016    0.000    0.023    0.000 patch_socket.py:40(recv)
    20000    0.014    0.000    0.014    0.000 {method 'gets' of 'hiredis.Reader' objects}
    10000    0.013    0.000    0.016    0.000 patch_socket.py:34(sendall)
    10000    0.013    0.000    0.016    0.000 _compat.py:18(<lambda>)
    10000    0.011    0.000    0.011    0.000 {method 'endswith' of 'str' objects}
    10000    0.010    0.000    0.010    0.000 {method 'feed' of 'hiredis.Reader' objects}
    10000    0.007    0.000    0.007    0.000 {method 'pop' of 'list' objects}
    10000    0.005    0.000    0.005    0.000 benchmark.py:14(release)
    10000    0.005    0.000    0.005    0.000 benchmark.py:11(get_connection)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

Use `redis._pack` c extension:

```
10000 loops, best of 3: 31.3 usec per loop
         250002 function calls in 0.547 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10000    0.075    0.000    0.437    0.000 client.py:387(execute_command)
    10000    0.069    0.000    0.122    0.000 connection.py:203(read_response)
    10000    0.059    0.000    0.059    0.000 {redis._pack._pack_command}
    10000    0.036    0.000    0.229    0.000 client.py:402(parse_response)
    10000    0.028    0.000    0.465    0.000 client.py:777(set)
    10000    0.026    0.000    0.159    0.000 connection.py:334(read_response)
    10000    0.026    0.000    0.124    0.000 connection.py:330(send_command)
    10000    0.023    0.000    0.039    0.000 connection.py:311(send_packed_command)
    10000    0.023    0.000    0.023    0.000 patch_socket.py:17(start_replay)
    10000    0.023    0.000    0.531    0.000 benchmark.py:38(run_with_replay)
    10000    0.020    0.000    0.485    0.000 benchmark.py:28(bench)
    10000    0.018    0.000    0.034    0.000 client.py:261(<lambda>)
        1    0.017    0.017    0.547    0.547 <string>:1(<module>)
    10000    0.015    0.000    0.022    0.000 patch_socket.py:40(recv)
    20000    0.014    0.000    0.014    0.000 {isinstance}
    10000    0.014    0.000    0.016    0.000 patch_socket.py:34(sendall)
    20000    0.013    0.000    0.013    0.000 {method 'gets' of 'hiredis.Reader' objects}
    10000    0.012    0.000    0.016    0.000 _compat.py:18(<lambda>)
    10000    0.010    0.000    0.010    0.000 {method 'endswith' of 'str' objects}
    10000    0.009    0.000    0.009    0.000 {method 'feed' of 'hiredis.Reader' objects}
    10000    0.007    0.000    0.007    0.000 {method 'pop' of 'list' objects}
    10000    0.005    0.000    0.005    0.000 benchmark.py:11(get_connection)
    10000    0.004    0.000    0.004    0.000 benchmark.py:14(release)
    10000    0.003    0.000    0.003    0.000 {len}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

### CODE REVIEW

**Comment by AndreLouisCaron** [comment]
@yihuang Is there any plan to revive this PR?  Local testing with this merged shows impressive gains on pipelines with many commands in our application and I'd really like to see this in an official build!

**Comment by yihuang** [comment]
Since I didn't use this patch myself in production anymore, so I didn't follow redis-py' recent changes, and I don't think there are much interests to merge this into official anyway.
Instead I've made my own redis client (credis) which is written completely in cython with performance in mind. If you really need performance or appreciate a simpler api, I suggest you go with credis.

**Comment by winstonlin** [comment]
@andymccurdy  Is there still any interest in merging this pull request? If all that is necessary is to resolve the conflicts with the master, I can do that.

**Comment by joshowen** [comment]
There are certainly some of us lurking around here who are interested!

**Comment by vgoklani** [comment]
bump

**Comment by dejlek** [comment]
After 2+ years... Looks like there is no interest in merging this.

**Comment by judahrand** [comment]
Still interested! @andymccurdy

**Pull request closed without merging**
