### PR TITLE
Fix: zadd raises unhandled exception - fixes #954

### LINKED ISSUE #954: zadd raises TypeError exception
When i try 
to update score of non-existing field like this:
`r.zadd('fooset', 'xx', 'INCR', 10, 'bar')`
OR 
to update score of existing field like this:
`r.zadd('fooset', 'xx', 'INCR', 10, 'zoo')`

ZADD returns None and method is raising
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

### PR DESCRIPTION
**Pull request by nitingupta89**
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### CODE REVIEW

**Comment by nitingupta89** [comment]
Fixes #954

**Comment by nitingupta89** [comment]
@andymccurdy Please merge

**Comment by andymccurdy** [comment]
This is because the existing `ZADD` command doesn't support any of the newer options because of the method signature. This will be fixed when the other ZADD options get added, but it'll be a backwards incompatible and need to wait for 3.0

**Comment by andymccurdy** [comment]
Fixed in redis-py 3.0

**Pull request closed without merging**
