### PR TITLE
Implemented support for the GEO commands for Redis 3.2.0

### PR DESCRIPTION
**Pull request by pfreixes**
The following commands have been implemented GEOADD, GEODIST,
GEOHASH, GEOPOS, GEORADIUS, GEORADIUSBYMEMBER.

### CODE REVIEW

**Comment by andymccurdy** [comment]
Thanks. I noticed you left all the return values as strings. It might be nice to convert some of them to Python types. Specifically:

GEOADD returns an int
GEODIST returns a double
GEORADIUS with the WITHDIST option returns a double

Thoughts?

**Comment by pfreixes** [comment]
@andymccurdy fair enough, sorry for the delay I was busy with some work stuff. Before tomorrow it will be done.

Cheers

**Comment by pfreixes** [comment]
A bit later but at last committed a new version where geo commands return Python native types, you can found these types in the UnitTests [1]

[1] https://github.com/andymccurdy/redis-py/pull/747/commits/f1abb79fb28ce58035e0a1d5c93688fb4d37f968

**Comment by andymccurdy** [comment]
Looks great, thanks. I'm merging now.

Question: Should we be returning doubles rather than floats? The GEO command docs [1] indicate the redis server returns doubles. Do Python floats offer enough precision?

[1] http://redis.io/commands/geodist

**Comment by benjolitz** [comment]
@andymccurdy Python floats are internally doubles.

You can see it here: https://github.com/python/cpython/blob/c30098c8c6014f3340a369a31df9c74bdbacc269/Include/floatobject.h#L17

**Pull request merged**
