### PR TITLE
Implement/test LOLWUT command

### PR DESCRIPTION
**Pull request by brainix**
### Pull Request check-list

- [x] Does `$ tox` pass with this change (including linting)?
- [x] Does travis tests pass with this change (enable it first in your forked repo and wait for the travis build to finish)?
- [x] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### Description of change

Implement/test [`LOLWUT`](https://redis.io/commands/lolwut) command

This is a lot of fun to play with:

```python
>>> from redis import Redis
>>> redis = Redis()
>>> print(redis.lolwut(5, 6, 7, 8).decode('utf-8'))
⣴⣶⣶⣶⣶⡆
⣿⣿⣿⣿⣿⡇
⠹⡿⠟⣿⡿⠃
⠀⠀⠀⠀⠀⠀
Georg Nees - schotter, plotter on paper, 1968. Redis ver. 6.0.10

>>> print(redis.lolwut(5, 6, 7, 8).decode('utf-8'))
⢰⣶⣶⣶⣶⡆
⢿⣿⣿⣿⣿⠁
⠸⡿⢿⠿⡿⠃
⠀⠀⠀⠀⠀⠀
Georg Nees - schotter, plotter on paper, 1968. Redis ver. 6.0.10

>>> print(redis.lolwut(5, 6, 7, 8).decode('utf-8'))
⢰⣶⣶⣶⣶⡆
⣸⣿⣿⣻⣿⡅
⠿⡿⠻⠿⠿⠁
⠀⠀⠀⠀⠀⠀
Georg Nees - schotter, plotter on paper, 1968. Redis ver. 6.0.10

>>>
```

### CODE REVIEW

**Comment by 2014BDuck** [comment]
LOL, this one is interesting. Might be not useful in real project tho.
Thanks :P

**Comment by brainix** [comment]
@andymccurdy - I'm not sure if a documentation update is warranted for this change. What do you think?

If you'd like for this to be documented, where should I document it? Any tips?

Thanks!

**Comment by chayim** [comment]
Can you merge master in and resolve conflicts. Once it passes all tests, I'd be happy to.

**Comment by brainix** [comment]
I made a mess out of this branch. Recreating...

**Pull request closed without merging**
