### PR TITLE
Implemented support for the GEO commands for Redis 3.2.0

### PR DESCRIPTION
**Pull request by pfreixes**
The following commands have been implemented GEOADD, GEODIST,
GEOHASH, GEOPOS, GEORADIUS, GEORADIUSBYMEMBER. /cc #636

### CODE REVIEW

**Comment by pfreixes** [comment]
@andymccurdy any thoughts about this PR?

**Comment by thejpanganiban** [comment]
Nice! :+1:

**Comment by andymccurdy** [comment]
@pfreixes I was going to merge this today. Did you remove it?

**Comment by pfreixes** [comment]
Yups I was working on my mater rebasing from your master, Ive moved the branch to another one. Give me 1 minute

**Comment by pfreixes** [comment]
https://github.com/andymccurdy/redis-py/pull/747 /cc @andymccurdy

**Comment by AbdullahAli** [comment]
Can you please release this version so it is installable via pip @pfreixes ?

**Comment by pfreixes** [comment]
@AbdullahAli I cant do it, its up to @andymccurdy

**Comment by vietvudanh** [comment]
I was wondering where it is, it turns out haven't been released yet. Guys? @andymccurdy

**Pull request closed without merging**
