### PR TITLE
change exists to variodic

### PR DESCRIPTION
**Pull request by charsyam**
A days ago, redis change exists command can be variodic in unstable branch.

so I send pr for this :)

```
set a 123
set b  123
exists a b
:2
```

### CODE REVIEW

**Comment by charsyam** [comment]
@andymccurdy Redis 3.0.3 is out. and It contains variadic exists :)

**Comment by Suor** [comment]
+1

**Comment by andymccurdy** [comment]
fixed in redis-py 3.0

**Comment by charsyam** [comment]
Thanks @andymccurdy

**Pull request closed without merging**
