### PR TITLE
Add a count parameter to lpop/rpop for redis >= 6.2.0

### PR DESCRIPTION
**Pull request by wavenator**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Does travis tests pass with this change (enable it first in your forked repo and wait for the travis build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Comment by chayim** [comment]
@wavenator Mind updating your branch with the latest master. CI has moved to GitHub actions, and the unit test were fixed. Happy to review when ready.

**Comment by wavenator** [comment]
@chayim Thanks for your reply. My tests have been fixed. One more test failed that wasn't mine. I appreciate your help with this. By the way, I hope you squash all my commits.

**Comment by chayim** [comment]
@wavenator Looks great, and checks out against the [lpop](https://redis.io/commands/LPOP) and [rpop](https://redis.io/commands/RPOP) docs.  I think the unit test failed because the client kill run (my change a while back!) didn't properly turf all connections. I'm going to play with this a bit more, to be sure - and re-run the action accordingly.

**Comment by wavenator** [comment]
> @wavenator Looks great, and checks out against the [lpop](https://redis.io/commands/LPOP) and [rpop](https://redis.io/commands/RPOP) docs. I think the unit test failed because the client kill run (my change a while back!) didn't properly turf all connections. I'm going to play with this a bit more, to be sure - and re-run the action accordingly.

I will be more than happy to help you if you need it!

**Comment by chayim** [comment]
@wavenator I have a [PR](https://github.com/andymccurdy/redis-py/pull/1536) up, purely to update to the latest redis-docker (and fix client kill), which will hence pass yours. But, I uncovered a flaky test (this same one!) as my reminder. I've asked @AvitalFineRedis to fix the flaky test from her PR, so that I don't blindly merge my change.

redis-py had a period of time where unit tests in master were failing, so my goal is to keep those, always passing - as first order.

**Comment by chayim** [comment]
Validated with latest master, tests pass.

@wavenator Thanks a tonne for your contribution, and patience in the back-and-forth. Much obliged!

**Pull request merged**
