### PR TITLE
Allow setting clientname during connection construction

### PR DESCRIPTION
**Pull request by Habbie**
This makes the SELECT also log the client name, streamlining the
logging. Default clientnames have been provided which in some cases
will already make debugging easier even if no explicit clientname
has been provided.

### CODE REVIEW

**Comment by Habbie** [comment]
I see I'm failing some tests here; will try to look at that this week. Comments are welcome meanwhile!

**Comment by AngusP** [comment]
@Habbie this would be a neat feature, though according to [redis.io/commands/client-setname](https://redis.io/commands/client-setname) you need to ensure the clientname contains no spaces, otherwise it'll get a  `(error) ERR Syntax error...` from Redis.

Also [here](https://github.com/andymccurdy/redis-py/pull/802/files#diff-b3be2d0fa4e0cf1f1c403f2de43ecdb4R539) you check if a client name is given, which it will always be as there's a default provided. If the default were `None`, and the check was instead `if type(self.clientname) is str` (or something similar) you'd be able to disable its use, which would be useful to people using redis-py in performant environments where many clients may be spawning, where the traffic from `CLIENT SETNAME`s would be unnecessary bloat

**Comment by Habbie** [comment]
Yes, I got around to taking a short look and noticed whitespace issues. I'll try to get back to it soon.

**Comment by daveisfera** [comment]
This would be a very helpful feature. What needs to be done to get this merged?

**Comment by andymccurdy** [comment]
I agree, this is a nice feature. Happy to merge once the tests pass.

**Comment by Habbie** [comment]
Hello! I'm glad this is getting some attention.

One, some context, I also filed https://github.com/antirez/redis/pull/3592 which would make this way more useful.

Two, I'll see what I can do about the tests sometime soon.

**Comment by andymccurdy** [comment]
I've fixed the tests and cleaned this up a bit. The `client_name` argument can now be passed to `Redis` or `ConnectionPool` instances. `CLIENT SETNAME` is only executed if the `client_name` argument is supplied. `client_name` also only appears within the `repr()` strings if `client_name` is supplied.

These changes have been merged into master and will go out in the next release. Thanks!

**Comment by Habbie** [comment]
Wonderful, thank you for compensating for my lack of action on this!

**Pull request closed without merging**
