### PR TITLE
Add support for specifying the token when acquiring a lock

### PR DESCRIPTION
**Pull request by dave-nm**
- [X] Does `$ python setup test` pass with this change (including linting)? (pytest passes but I'm not sure how to run the linting)
- [ ] Does travis tests pass with this change (enable it first in your forked repo and wait for the travis build to finish)? (I don't know how to do this)
- [X] Is the new or changed code fully tested? (Added test for the bug fix and the new feature)
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? (I updated the documentation of the function and didn't see anything else that I'm supposed to do)

### Description of change
*  Allowed `token` to be specified in `Lock.acquire()`
* Fixed `Lock.locked()` to verify the value of the token

### CODE REVIEW

**Comment by daveisfera** [comment]
Are you ok if I add a parameter that defaults to `True` to maintain the current behavior and if set to `False` will do the new behavior?

**Comment by daveisfera** [comment]
I added a commit with what that would look like.

**Comment by andymccurdy** [comment]
I think it would be better to have a separate method to indicate whether the current lock instance owns the lock. Perhaps `owned()`?

**Comment by daveisfera** [comment]
Oh sorry, did I set this up to merge into a branch instead of `master`? Can you merge it into `master`?

**Comment by daveisfera** [comment]
oh ok. thanks for merging this. We're looking forward to the 3.1.0 release so we can dump our homegrown lock, now that this one has `reacquire()` and the ability to specify `token`.

**Comment by andymccurdy** [comment]
ok, it's been merged to master. Thanks!

**Pull request merged**
