### PR TITLE
[WIP] Zadd options

### PR DESCRIPTION
**Pull request by chester89**

### CODE REVIEW

**Comment by chester89** [comment]
As I suspected, Travis CI has earlier Redis version bundled - 2.8.19. So, this is not finished

**Comment by andymccurdy** [comment]
According to http://redis.io/commands/zadd, the options are specified in the form of `ZADD [option] score member`. There don't seem to be separate commands for each option like you're using here.

**Comment by chester89** [comment]
I don't mind using a parameter for this - just seemed clearer to create separate methods

**Comment by andymccurdy** [comment]
I'm not talking about the API redis-py presents. I'm talking about the command names. Is there a command named ZADDNX? There isn't according to the docs.

**Comment by chester89** [comment]
I see - let me check for that

**Comment by chester89** [comment]
yep, you're right - I'll update the code

**Comment by chester89** [comment]
ok, it's working. do you want me to update travis to install 3.0.2
@andymccurdy?

2015-07-21 2:05 GMT+03:00 Andy McCurdy <notifications@github.com>:

> I'm not talking about the API redis-py presents. I'm talking about the
> command names. Is there a command named ZADDNX? There isn't according to
> the docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andymccurdy/redis-py/pull/638#issuecomment-123083445>.
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
After I clean up mapping of command name to result type, of course)

2015-07-22 0:17 GMT+03:00 Gleb Chermennov <thebitterend77@gmail.com>:

> ok, it's working. do you want me to update travis to install 3.0.2
> @andymccurdy?
>
> 2015-07-21 2:05 GMT+03:00 Andy McCurdy <notifications@github.com>:
>
>> I'm not talking about the API redis-py presents. I'm talking about the
>> command names. Is there a command named ZADDNX? There isn't according to
>> the docs.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/andymccurdy/redis-py/pull/638#issuecomment-123083445>
>> .
>>
>
>
>
> --
> Yours faithfully,
> Gleb
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
If you need anything else, let me know

2015-07-22 14:04 GMT+03:00 Gleb Chermennov <thebitterend77@gmail.com>:

> After I clean up mapping of command name to result type, of course)
>
> 2015-07-22 0:17 GMT+03:00 Gleb Chermennov <thebitterend77@gmail.com>:
>
>> ok, it's working. do you want me to update travis to install 3.0.2
>> @andymccurdy?
>>
>> 2015-07-21 2:05 GMT+03:00 Andy McCurdy <notifications@github.com>:
>>
>>> I'm not talking about the API redis-py presents. I'm talking about the
>>> command names. Is there a command named ZADDNX? There isn't according to
>>> the docs.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/andymccurdy/redis-py/pull/638#issuecomment-123083445>
>>> .
>>>
>>
>>
>>
>> --
>> Yours faithfully,
>> Gleb
>>
>
>
>
> --
> Yours faithfully,
> Gleb
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
Looks like [we're not done] (https://github.com/antirez/redis/issues/2697)

**Comment by HeartSaVioR** [comment]
@chester89 
https://github.com/antirez/redis/issues/2697 is just my strong opinion, and antirez doesn't respond it yet.
Btw, if you think my opinion is right, please vote (:+1: seems OK) to https://github.com/antirez/redis/issues/2697 for letting antirez know about it.
Thanks!

**Comment by PetaPetaPeta** [comment]
What is the status on this pull request? It seems like antirez has made his opinion clear in the linked discussion.

**Comment by chester89** [comment]
Yeah, sorry for the delay, I need to update it a little bit. Will do on a
weekend

2015-10-23 11:29 GMT+03:00 Peter Poulsen <notifications@github.com>:

> What is the status on this pull request? It seems like antirez has made
> his opinion clear in the linked discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andymccurdy/redis-py/pull/638#issuecomment-150511162>.
>



-- 
Yours faithfully,
Gleb

**Comment by PetaPetaPeta** [comment]
Let me know if I can do anything to help!

**Comment by mathieulongtin** [comment]
I'd suggest adding `CH` for `zaddxx`, since otherwise it will always return 0.
`CH` for `zaddnx` makes no sense.

`NX` and `XX` can also be options with `INCR`.

So you need to support multiple options.

**Comment by va1en0k** [comment]
any news on this one?

**Comment by PetaPetaPeta** [comment]
Should this be merged in or should it wait until the new kwargs syntax is introduced?

I can make the changes that @mathieulongtin suggested, but I would like confirmation before I start the implementation.

**Comment by chester89** [comment]
I hear you, let me look this over

2015-12-29 1:44 GMT+03:00 Peter Poulsen <notifications@github.com>:

> Should this be merged in or should it wait until the new kwargs syntax is
> introduced?
>
> I can make the changes that @mathieulongtin
> <https://github.com/mathieulongtin> suggested, but I would like
> confirmation before I start the implementation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andymccurdy/redis-py/pull/638#issuecomment-167672915>.
>



-- 
Yours faithfully,
Gleb

**Comment by mathieulongtin** [comment]
Another option, since at least Python 3.6, we can do this:

    def zadd(self, key, *args, nx=False, xx=False, ch=False, **kwargs):

This wouldn't change the current usage, except if you were doing `redis.zadd(key, cx=24)`

Or a 2.7 thing:

    def zadd_options(self, key, values, nx=False, xx=False, ch=False):

Where `values` is either a dict, or a list or pairs.

**Comment by andymccurdy** [comment]
Fixed in redis-py 3.0

**Pull request closed without merging**
