### PR TITLE
Adding Sentinel Commands

### PR DESCRIPTION
**Pull request by otherpirate**
Sentinel API [commands](https://redis.io/topics/sentinel)

### CODE REVIEW

**Comment by otherpirate** [comment]
@andymccurdy Could you please review this PR?

**Comment by lalinsky** [comment]
There are already sentinel commands in `redis.client`, I think these should be added there:

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L792

**Comment by otherpirate** [comment]
What do you think @andymccurdy ? Should I take @lalinsky suggestion?

**Comment by chayim** [comment]
@otherpirate Thanks for the contribution. This is great! I'd like to get it in right after [this pr](https://github.com/andymccurdy/redis-py/pull/1534) if that's alright with you.

Alternatively if this is no longer active, I'll progress with it. Please let me know!

**Pull request closed without merging**
