### PR TITLE
Skip 64-bit specific tests. (Closes: #899)

### PR DESCRIPTION
**Pull request by lamby**
For #899

### CODE REVIEW

**Comment by lamby** [comment]
Gentle ping on this?

**Comment by andymccurdy** [comment]
If you can fix the pep8 issues I'll merge this. Don't worry about the py2.6 errors, we're no longer supporting 2.6.

**Comment by lamby** [comment]
> If you can fix the pep8 issues I'll merge this.

Whoops, missed that failure. All passing now and rebased against `master`.

**Comment by andymccurdy** [comment]
Thanks!

**Pull request merged**
