### PR TITLE
fix problem when using geopos on unexistent hash member

### PR DESCRIPTION
**Pull request by categulario**

### CODE REVIEW

**Comment by andymccurdy** [comment]
Should `GEOPOS` instead return just `None` (instead of `[None, None]`) in the case of a non-existent hash member? That's what redis-cli does according to: https://redis.io/commands/geopos. And it seems slightly easier to test for in calling code as well by simple saying:

```python
position = r.geopos('foo')
if position is None:
    # we don't know about this key
```

rather than:

```python
position = r.getpos('foo')
if position == [None, None]:
    # we don't know about this key
```

**Comment by categulario** [comment]
I was thinking about querying for a list of members and you get an array of
responses according to the item being found or not, which is kind of
consistent

**Comment by categulario** [comment]
Reading the GEOPOS documentation in redis.io says

> Non existing elements are reported as NULL elements of the array

The output from redis-cli is also an array of nils, which is consistent with the example they give in the same page.

**Comment by andymccurdy** [comment]
I completely misinterpreted the GEOPOS command. You're completely correct. Merging now.

**Comment by NoneGG** [comment]
The test case may need to be tested with newer version of redis.
In my dev env(with redis 3.2.1), `$0` will be returned if command like `geopos a b c` is sent.
But in my colleague's env(with redis 4.0), the test passed.

**Comment by andymccurdy** [comment]
@NoneGG Nice catch. I just saw the note about this in the Redis 4.0 patch notes.

I've just committed a fix to the test suite.

**Pull request merged**
