### PR TITLE
Added GET argument to SET command

### PR DESCRIPTION
**Pull request by 2014BDuck**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `$ tox` pass with this change (including linting)?
- [X] Does travis tests pass with this change (enable it first in your forked repo and wait for the travis build to finish)?
- [X] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Issue: https://github.com/andymccurdy/redis-py/issues/1411

Added GET argument to SET command, new in Redis 6.2: https://redis.io/commands/set

### CODE REVIEW

**Comment by 2014BDuck** [comment]
To handle this, the `read_response()` method in `connection.py` may need to change a little bit.
When redis return `'+OK'` or `'$2'` (and a "OK" string value), they will be parsed into `b'OK'` in `read_response()`. 

What do you think

**Comment by andymccurdy** [comment]
This looks good. I'd like to wait to merge until Redis 6.2 is released so that we can include it in the unit tests.

**Comment by 2014BDuck** [comment]
Hmm but it's not working now. There is no way to tell the difference between 'OK' (bool value) and 'OK' (string value, return when ''get'' param is set to True) in `client.py`.
```
r.set(1,'OK')     # we got b'OK' response
r.set(1,'foo',get=True)  # we got b'OK' again and will be parsed as bool value
```

this must be solve if we want to add 'get' argument to the set command. Will take a look tomorrow

**Comment by andymccurdy** [comment]
This should be pretty easy to solve.

```python
def set(self, ..., get=False):
    options = {}
    ...
    if get:
        pieces.append(b'GET')
        options['get'] = True

    return self.execute_command(*pieces, **options)
```

Then we make a response callback for `SET`:

```python
def parse_set(response, **options):
    if options.get('get'):
        # return the string
    # return the boolean
```

**Comment by 2014BDuck** [comment]
haha allright. I will deal it in this way. I thought it should be more concise before, without passing any extra argument.

will catch it up tomorrow.

**Comment by andymccurdy** [comment]
This looks good. Thanks! Tagging this as Redis 6.2 and will merge once the server is released.

**Comment by chayim** [comment]
Thank you for your contribution @2014BDuck. I just merged, and validated with redis server 6.2.5. Approving, and merging into master.

**Pull request merged**
